### ISSUE TITLE
Missing files and errors

### ISSUE THREAD

**Issue by whuwy0419** [SumanM47/Kryging#1]
% RestoreTools
path([directory, '/RestoreTools/Classes'], path)
path([directory, '/RestoreTools/TestData'], path)

% Regularization Tools
path([directory, '/REGU'], path)

These files are not provided in the codes.

Meanwhile, the DEMO cannot run due to the following errors.

Error HyBR_plain_lsmrset>checkfield (line 235)
Invalid value for OPTIONS parameter Lambda: must be a real non-negative scalar.

Error HyBR_plain_lsmrset (line 181)
        checkfield(Names{j,:},arg);

Error obj_func_ML_prof (line 68)
  input = HyBR_plain_lsmrset('Iter', maxit, 'Reorth',
  'off','Mu',0,'Lambda',lambda,'Sigma_e',sigma_e,'Grad',false);

Error
Kryging_est>@(th)obj_func_ML_prof(th,xmin,xmax,nvec,nu_opt,theta,R_nm,A_nm,dnm(:),X(nmi,:),maxit)
(line 49)
ftm = @(th) obj_func_ML_prof(th,xmin,xmax,nvec,nu_opt,theta,R_nm,
A_nm,dnm(:),X(nmi,:),maxit);

Error fminunc (line 296)
      [f,GRAD,HESS] = feval(funfcn{3},x,varargin{:});

Error Kryging_est (line 57)
[theta_est,fval,~,optout] = fminunc(ftm,x0,options);

Error Kryging_wocv (line 53)
[x_est, y_est, theta_est, numit, xl, xu, yl, yu] =
Kryging_est(Initvec(4:end),Initvec(3),Initvec(2),nu,Initvec(1),d(:),X,nmi,xmin,xmax,nvec,Anew,R,k,theta,W);

Error DEMO (line 59)
[x,y,theta,numit,tim,xl,xu,yl,yu] = Kryging_wocv(d,s,A,nu,X,initvec,maxit);

Failure in initial objective function evaluation. FMINUNC cannot continue.

**Comment by SumanM47** [comment]
Thanks for raising the issues. The files were unnecessary for Kryging application and were therefore not provided. It's been commented out to reflect so.

The error in the DEMO.m file has been taken care of and should run as it is.

**Comment by whuwy0419** [comment]
Thank you for fixing these issues.
